substitutions:
  name: mulbetet-house
  platform: ESP8266
  board: d1_mini
  wifi_ssid: "C64_things"
  wifi_password: !secret wifi.networks.password.things
  ip_address: 192.168.5.5

esphome:
  name: $name
  platform: $platform
  board: $board

<<: !include common.yaml

# Enable logging
logger:
  level: DEBUG

web_server:

ota:
  password: !secret ota.password


status_led:
  pin: 2

dallas:
  - pin: D1
    update_interval: 30s
    
sensor:
  - platform: pulse_counter
    id: heater_power
    pin: 
      number: D3
      mode: INPUT_PULLUP
    name: 'Heater Power'
    icon: mdi:power-plug
    unit_of_measurement: 'kW'
    accuracy_decimals: 4
    filters:
      - multiply: 0.006
    total:
      id: heaterEnergy
      device_class: energy
      name: 'Heater Energy'
      icon: mdi:flash
      unit_of_measurement: 'kWh'
      accuracy_decimals: 2
      filters:
        - filter_out: nan
        - multiply: 0.0001        

  - platform: dallas
    address: 0x5E0008025BD2EF10
    name: "Livingroom"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - filter_out: nan
      - lambda: if(x<85){return x;} else return {};

  - platform: dallas
    address: 0x28FF3E4C310400D2
    name: "Sauna"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - filter_out: nan
      - lambda: if(x<85){return x;} else return {};

  - platform: dallas
    address: 0xFF0008025BBC6410
    # address: 0xFF0008025BBC6410
    name: "Basement"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - filter_out: nan
      - lambda: if(x<85){return x;} else return {};

  - platform: dallas
    address: 0x470008025BC65310
    name: "Outside"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - filter_out: nan
      - lambda: if(x<85){return x;} else return {};
