esphome:
  name: mulbetet
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
  - ssid: "aceone"
    password: !secret wifi.networks.password
    priority: 2.0
  # - ssid: "C64"
  #   password: !secret wifi.networks.password
  #   priority: 1.0
  - ssid: "C64_things"
    password: !secret wifi.networks.password.things
    priority: 2.0
  
 # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi.ap.password

  manual_ip:
    static_ip: 192.168.5.5
    gateway: 192.168.5.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4

mqtt:
  broker: aceone.se
  username: !secret mqtt.username
  password: !secret mqtt.password


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api.password

ota:
  password: !secret ota.password

dallas:
  - pin: D1
    update_interval: 30s
    
sensor:
  - platform: pulse_counter
    id: heater_power
    pin: 
      number: D3
      mode: INPUT_PULLUP
    name: 'Heater Power'
    icon: mdi:power-plug
    unit_of_measurement: 'kW'
    accuracy_decimals: 4
    filters:
      - multiply: 0.006
    total:
      id: heaterEnergy
      device_class: energy
      name: 'Heater Energy'
      icon: mdi:flash
      unit_of_measurement: 'Wh'
      accuracy_decimals: 2
      filters:
        - multiply: 0.1        

  - platform: dallas
    address: 0x5E0008025BD2EF10
    name: "Livingroom"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - lambda: if(x<85){return x;} else return {};

  - platform: dallas
    address: 0x28FF3E4C310400D2
    name: "Sauna"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - lambda: if(x<85){return x;} else return {};

  - platform: dallas
    address: 0xFF0008025BBC6410
    # address: 0xFF0008025BBC6410
    name: "Basement"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - lambda: if(x<85){return x;} else return {};

  - platform: dallas
    address: 0x470008025BC65310
    name: "Outside"
    resolution: 10
    unit_of_measurement: 째C
    accuracy_decimals: 2
    filters:
      - lambda: if(x<85){return x;} else return {};
