esphome:
  name: radhuset-temp
  platform: ESP8266
  board: esp01

<<: !include wifi.yaml
wifi:
  networks:
  - ssid: "radhuset"
    password: "feelgood"
    priority: 2.0

  manual_ip:
    static_ip: 192.168.10.5
    gateway: 192.168.10.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4

mqtt:
  broker: aceone.se
  username: !secret mqtt.username
  password: !secret mqtt.password


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api.password

ota:
  password: !secret ota.password

dallas:
  - pin: GPIO00
    update_interval: 30s


# [11:21:07][D][dallas.sensor:082]:     0xD6031702E676FF28
# [11:21:07][D][dallas.sensor:082]:     0x11031702EE25FF28
# [11:21:07][D][dallas.sensor:082]:     0xF3041702D52FFF28

# Dallas Sensor (ds18b20)
sensor:
  - platform: dallas
    address: 0x11031702EE25FF28
    name: "Staircase radhuset"
    resolution: 10
    unit_of_measurement: °C
    accuracy_decimals: 2

  - platform: dallas
    address: 0xD6031702E676FF28
    name: "Outside radhuset"
    resolution: 10
    unit_of_measurement: °C
    accuracy_decimals: 2
    filters:
      - lambda: |-
          if (x < 85.0) return x;
          else return {};
  - platform: dallas
    address: 0xF3041702D52FFF28
    name: "Basement radhuset"
    resolution: 10
    unit_of_measurement: °C
    accuracy_decimals: 2


