esphome:
  name: radhuset_energy
  platform: ESP8266
  board: esp01

<<: !include wifi.yaml

mqtt:
  broker: aceone.se
  username: !secret mqtt.username
  password: !secret mqtt.password


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api.password

ota:
  password: !secret ota.password

captive_portal:

sensor:
  - platform: pulse_counter
    id: main_power
    pin: 
      number: GPIO02
      mode: INPUT_PULLUP
    name: 'Power Meter Main'
    icon: mdi:power-plug
    unit_of_measurement: 'kW'
    accuracy_decimals: 4
    filters:
      - multiply: 0.06

    total:
      id: main_energy
      name: 'Energy Meter Main'
      icon: mdi:flash
      unit_of_measurement: 'Wh'
      accuracy_decimals: 2
      
